name: Update leaderboard on PR Merge.

on:
  pull_request:
    branches:
      - development
    types:
      [closed]

jobs:
  leaderboard_evaluation:
    runs-on: ubuntu-latest
    steps:
      - name: Check if there are any changes in submissions dir
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          filters: |
            src:
              - 'session_2/challenge/submissions/**'
          list-files: "shell"

      - name: Print changed files
        run: |
          echo '${{ toJSON(steps.changes.outputs) }}'

      - if: ${{ (steps.changes.outputs.src_count > 1) }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed('More than one submissions are not allowed at once.')          
                        
      # Update leaderboard only if single file is changed in submission dir
      - if: ${{ (steps.changes.outputs.src == 'true') && (steps.changes.outputs.src_count == 1) }}
        name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}        

      - if: ${{ (steps.changes.outputs.src == 'true') && (steps.changes.outputs.src_count == 1) }}
        name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - if: ${{ (steps.changes.outputs.src == 'true') && (steps.changes.outputs.src_count == 1) }}
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r session_2/challenge/requirements.txt

      - if: ${{ (steps.changes.outputs.src == 'true') && (steps.changes.outputs.src_count == 1) }}
        name: Run leaderboard update script
        id: leaderboard-update
        run: |
          cd session_2/challenge
          filename=$(basename "${{ steps.changes.outputs.src_files }}")
          filename_without_extension="${filename%.*}"  # Remove extension          
          python -m scripts.leaderboard --github_user="${{ github.actor }}" --prompt="$filename_without_extension"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Updated leader board'
          add: 'session_2/challenge/leaderboard.md'

      #   # Commit the updated leaderboard
      # - if: ${{ (steps.changes.outputs.src == 'true') && (steps.changes.outputs.src_count == 1) }}
      #   name: Commit updated leaderboard
      #   id: commit-leaderboard
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
      #     git add session_2/challenge/leaderboard.md
      #     git commit -m "Update leaderboard"
      #     git push -f origin HEAD:${{ github.ref }}


      #   # Print the commit SHA for reference
      # - if: ${{ (steps.changes.outputs.src == 'true') && (steps.changes.outputs.src_count == 1) }}
      #   name: Print Commit SHA
      #   run: |
      #     echo "Commit SHA: ${{ steps.commit-leaderboard.outputs.commit_sha }}"